<div id="cadastro-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title"></h4>      
            </div>
            <div class="modal-body">
                <section></section>
                <?php
                    echo $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('descricao')); ?>
                    <p class="content-redirect text-danger"></p>
                </div>
            </div>
            <div class="modal-footer">
                <a 
                    href="#" 
                    class="btn btn-success enviar" 
                    value="Enviar" 
                    name="submit"
                    data-url-request="/application/index/cadastro"
                    data-url-redirect="/"
                >
                    Enviar
                </a>
                <?php echo $this->form()->closeTag(); ?>
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>